ProjektZaliczeniowyDziekanat/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using ProjektZaliczeniowyDziekanat.DAL.Models;
using ProjektZaliczeniowyDziekanat.Interfaces;
using Microsoft.AspNetCore.Http;
using System.Threading.Tasks;
using System.Collections.Generic;
using System.Linq;

namespace ProjektZaliczeniowyDziekanat.Controllers
{
    public class StudentController : Controller
    {
        private readonly IObslugaStudent obslugaStudent;
        

        public StudentController(IObslugaStudent obslugaStudent)
        {
            this.obslugaStudent = obslugaStudent;
        }

        [HttpGet]
        [Route("Student/Home")]
        public IActionResult Index()
        {
            Student student = obslugaStudent.ZalogowanyStudent(HttpContext.Session.GetInt32("studentID"));

            if (student == null)
                return BadRequest();
            else
                return View(student);
        }

        [HttpGet]
        public async Task<IActionResult> Dane()
        {           
            StudentDTO studentDTO = await obslugaStudent.ZalogowanyStudentDTOAsync(HttpContext.Session.GetInt32("studentID"));

            if (studentDTO == null)
                return BadRequest();

            else
            {
                Platnosc platnosc = obslugaStudent.ZnajdzPlatnosc(HttpContext.Session.GetInt32("studentID"));
                if (platnosc == null)
                {
                    ViewData["platnosc"] = "NIE OPŁACONO";
                    ViewData["dataPlatnosci"] = "NIE OPŁACONO";
                }
                else
                {
                    ViewData["platnosc"] = platnosc.Kwota;
                    ViewData["dataPlatnosci"] = platnosc.DataPlatnosci.ToString("d");
                }

                return View(studentDTO);
            }
        }


        [HttpGet]
        public async Task<IActionResult> PlanZajec(string sortOrder, string searchString)
        {
            Student ZalStudent = obslugaStudent.ZalogowanyStudent(HttpContext.Session.GetInt32("studentID"));

            if (ZalStudent == null)
                return BadRequest();
            else
            {
                ViewData["DateSortPar"] = String.IsNullOrEmpty(sortOrder) ? "date_desc" : "";
                ViewData["NameSortPar"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
                ViewData["CurrentFilter"] = searchString;
                var list = await obslugaStudent.WyswietlZajeciaAsync(ZalStudent, sortOrder, searchString);


                return View(list);
            }
        }

        [HttpGet]
        public IActionResult Contact()
        {
            var student =  obslugaStudent.ZalogowanyStudent(HttpContext.Session.GetInt32("studentID"));
            ViewData["nadawca"] = $"{student.Imie} {student.Nazwisko}";
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Oceny()
        {
            List<StudentOceny> oceny = await obslugaStudent.PobierzOcenyStudentaAsync(HttpContext.Session.GetInt32("studentID")); 
            if(oceny.Any())
            {
                oceny.ForEach(x => x.Zajecia = obslugaStudent.PobierzZajecia(x.ZajeciaID));
                oceny.ForEach(x => x.Student = obslugaStudent.ZalogowanyStudent(x.StudentID));

                return View(oceny);
            }

            return View(oceny);
        }
    }
}

ProjektZaliczeniowyDziekanat/Controllers/WykladowcaController.cs
using Microsoft.AspNetCore.Mvc;
using ProjektZaliczeniowyDziekanat.DAL.Models;
using ProjektZaliczeniowyDziekanat.Interfaces;
using Microsoft.AspNetCore.Http;
using System.Threading.Tasks;

namespace ProjektZaliczeniowyDziekanat.Controllers
{
    public class WykladowcaController : Controller
    {
        private readonly IObslugaWykladowca obslugaWykladowca;

        public WykladowcaController(IObslugaWykladowca obslugaWykladowca)
        {
            this.obslugaWykladowca = obslugaWykladowca;
        }

        [HttpGet]
        [Route("Wykladowca/Home")]
        public async Task<IActionResult> Index()
        {
            Wykladowca wykladowca = await obslugaWykladowca.ZalogowanyWykladowcaAsync(HttpContext.Session.GetInt32("wykladowcaID"));

            if (wykladowca == null)
                return BadRequest();
            else
                return View(wykladowca);
        }

        [HttpGet]
        public async Task<IActionResult> PlanZajec()
        {
            Wykladowca ZalWykladowca = await obslugaWykladowca.ZalogowanyWykladowcaAsync(HttpContext.Session.GetInt32("wykladowcaID"));

            if (ZalWykladowca == null)
                return BadRequest();
            else
                return View(await obslugaWykladowca.WyswietlZajeciaAsync(ZalWykladowca));
        }

        [HttpGet]
        public async Task<IActionResult> Dane()
        {
            WykladowcaDTO ZalWykladowca = await obslugaWykladowca.ZalogowanyWykladowcaDTOAsync(HttpContext.Session.GetInt32("wykladowcaID"));

            if (ZalWykladowca == null)
                return BadRequest();
            else
                return View(ZalWykladowca);
        }

        [HttpGet]
        public async Task<IActionResult> Contact()
        {
            var wykladowca = await obslugaWykladowca.ZalogowanyWykladowcaAsync(HttpContext.Session.GetInt32("wykladowcaID"));
            ViewData["nadawca"] = $"{wykladowca.Imie} {wykladowca.Nazwisko}";
            return View();
        }

    }
}

ProjektZaliczeniowyDziekanat/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        body {
            background-image: url(../jpg/audit.jpg);
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-xl navbar-light bg-light shadow">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index"><h3>&nbsp;Wirtualny Dziekanat&nbsp;&nbsp;|&nbsp;&nbsp;</h3></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index"><h5 class="font-weight-normal">Strona główna</h5></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="PlanZajec"><h5 class="font-weight-normal">Plan Zajeć</h5></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Studenci"><h5 class="font-weight-normal">Studenci</h5></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Wykladowcy"><h5 class="font-weight-normal">Wykładowcy</h5></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Contact"><h5 class="font-weight-normal">Kontakt</h5></a>
                    </li>
                </ul>
                <span class="navbar-text">
                    <a asp-controller="Account" asp-action="Logout" class="text-decoration-none">Wyloguj</a>
                </span>
            </div>
        </div>
    </nav>
    <div class="container" id="bodyContainer">
        <main role="main" class="pb-3  justify-content-center align-items-center">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/script.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProjektZaliczeniowyDziekanat/Views/Shared/StudentLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        body {
            background-image: url(../jpg/audit.jpg);
            background-repeat: no-repeat;
            background-size: cover;  
            }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-xl navbar-light bg-light shadow">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Student" asp-action="Index"><h3>&nbsp;Wirtualny Dziekanat&nbsp;&nbsp;|&nbsp;&nbsp;</h3></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index"><h5 class="font-weight-normal">Strona główna</h5></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Dane"><h5 class="font-weight-normal">Dane</h5></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="PlanZajec"><h5 class="font-weight-normal">Plan Zajęć</h5></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Oceny"><h5 class="font-weight-normal">Oceny</h5></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Contact"><h5 class="font-weight-normal">Kontakt</h5></a>
                    </li>

                </ul>
                <span class="navbar-text">
                    <a asp-controller="Account" asp-action="Logout" class="text-decoration-none">Wyloguj</a>
                </span>
            </div>
        </div>
    </nav>
    <div class="container" id="bodyContainer">
        <main role="main" class="pb-3  justify-content-center align-items-center" >
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/script.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProjektZaliczeniowyDziekanat/Views/Shared/WykladowcaLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        body {
            background-image: url(../jpg/audit.jpg);
            background-repeat: no-repeat;
            background-size: cover;
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-xl navbar-light bg-light shadow">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Wykladowca" asp-action="Index"><h3>&nbsp;Wirtualny Dziekanat&nbsp;&nbsp;|&nbsp;&nbsp;</h3></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Wykladowca" asp-action="Index"><h5 class="font-weight-normal">Strona główna</h5></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Wykladowca" asp-action="Dane"><h5 class="font-weight-normal">Dane</h5></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Wykladowca" asp-action="PlanZajec"><h5 class="font-weight-normal">Plan Zajęć</h5></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Wykladowca" asp-action="Contact"><h5 class="font-weight-normal">Kontakt</h5></a>
                    </li>
                </ul>
                <span class="navbar-text">
                    <a asp-controller="Account" asp-action="Logout" class="text-decoration-none">Wyloguj</a>
                </span>
            </div>
        </div>
    </nav>
    <div class="container" id="bodyContainer">
        <main role="main" class="pb-3  justify-content-center align-items-center">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/script.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>